### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by tgnielse1145**

### CODE REVIEW

**Review by corey-buchanan — APPROVED** [review]
Looks good

**Review by VarunBhavya — CHANGES_REQUESTED** [review]
The code looks good, but I don't see the power measurement of each scenario in the readme file. Please integrate that into the readme file.

**Comment by tgnielse1145** [comment]
> The code looks good, but I don't see the power measurement of each scenario in the readme file. Please integrate that into the readme file.

I just added the values to our readme i must've forgot to push them before doing the pull request my bad

**Review by VarunBhavya — APPROVED** [review]
I appreciate you making the adjustments. Everything looks great now.

**Pull request merged**
